"""empty message

Revision ID: d31f72ae6973
Revises: 
Create Date: 2020-03-28 20:10:21.423848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31f72ae6973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huidig_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_huidig_student_email'), 'huidig_student', ['email'], unique=False)
    op.create_index(op.f('ix_huidig_student_name'), 'huidig_student', ['name'], unique=False)
    op.create_table('richting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_richting_name'), 'richting', ['name'], unique=False)
    op.create_table('statistics',
    sa.Column('rickroll_counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rickroll_counter')
    )
    op.create_table('toekomstig_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toekomstig_student_email'), 'toekomstig_student', ['email'], unique=False)
    op.create_index(op.f('ix_toekomstig_student_name'), 'toekomstig_student', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('car_color', sa.String(length=64), nullable=True),
    sa.Column('car_brand', sa.String(length=64), nullable=True),
    sa.Column('car_plate', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_car_brand'), 'user', ['car_brand'], unique=False)
    op.create_index(op.f('ix_user_car_color'), 'user', ['car_color'], unique=False)
    op.create_index(op.f('ix_user_car_plate'), 'user', ['car_plate'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('music_pref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('likes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('departure_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('departure_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_lat', sa.Float(precision=53), nullable=True),
    sa.Column('arrival_location_long', sa.Float(precision=53), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_departure_time'), 'route', ['departure_time'], unique=False)
    op.create_table('route_request',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='requeststatus'), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_request')
    op.drop_index(op.f('ix_route_departure_time'), table_name='route')
    op.drop_table('route')
    op.drop_table('music_pref')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_car_plate'), table_name='user')
    op.drop_index(op.f('ix_user_car_color'), table_name='user')
    op.drop_index(op.f('ix_user_car_brand'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_toekomstig_student_name'), table_name='toekomstig_student')
    op.drop_index(op.f('ix_toekomstig_student_email'), table_name='toekomstig_student')
    op.drop_table('toekomstig_student')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_richting_name'), table_name='richting')
    op.drop_table('richting')
    op.drop_index(op.f('ix_huidig_student_name'), table_name='huidig_student')
    op.drop_index(op.f('ix_huidig_student_email'), table_name='huidig_student')
    op.drop_table('huidig_student')
    # ### end Alembic commands ###
