"""empty message

Revision ID: fa2f35752643
Revises: d31f72ae6973
Create Date: 2020-03-28 20:24:03.292207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2f35752643'
down_revision = 'd31f72ae6973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huidig_student', sa.Column('richting', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'huidig_student', 'richting', ['richting'], ['id'])
    op.add_column('toekomstig_student', sa.Column('richting', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'toekomstig_student', 'richting', ['richting'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toekomstig_student', type_='foreignkey')
    op.drop_column('toekomstig_student', 'richting')
    op.drop_constraint(None, 'huidig_student', type_='foreignkey')
    op.drop_column('huidig_student', 'richting')
    # ### end Alembic commands ###
